export const GET_NOTIFICATIONS = 'GET_NOTIFICATIONS',
             READ_NOTIFICATION = 'READ_NOTIFICATION',
             READ_ALL_NOTIFICATIONS = 'READ_ALL_NOTIFICATIONS',
             REQUEST_NOTIFICATIONS = 'REQUEST_NOTIFICATIONS',
             REQUEST_READING_NOTIFICATION = 'REQUEST_READING_NOTIFICATION',
             REQUEST_READING_ALL_NOTIFICATIONS = 'REQUEST_READING_ALL_NOTIFICATIONS';
